content/docs/concepts/blockchain/account.md, content/docs/concepts/blockchain/block.md, content/docs/concepts/blockchain/validator.md, content/docs/concepts/transaction/bond.md, content/docs/concepts/transaction/fomart.md, content/docs/concepts/transaction/sortition.md, content/docs/concepts/transaction/transfer.md, content/docs/concepts/transaction/unbond.md, content/docs/concepts/transaction/withdraw.md
This PR moves field column first then size for field tables.
=> change column order in field tables

.github/workflows/deploy.yml
This PR optimize PNG images before uploading to server
=> chore: Optimizing PNG images

content/get-started/configuration.md, content/tutorials/grpc-basic-auth.md, content/tutorials/linux-systemd.md
This PR update these guides:
- How to Secure gRPC Using Basic Authentication
- How to Run Pactus with systemd on Linux
- Pactus Node Configuration
=> update user-guide docs

assets/css/custom.css, content/tutorials/grpc-sign-transactions.md, content/tutorials/pactus-shell.md, content/tutorials/reduce-network.md
Updating "How to Sign Transactions Using gRPC" document
=> update How to Sign Transactions Using gRPC document

static/swagger-ui/pactus.swagger.json
This PR fixes swagger HTTPS issue
=> fix: use https for swagger

static/swagger-ui/pactus.swagger.json
This PR remove https scheme from host
=> fix: remove scheme from host

content/protocol/consensus/protocol.md
This PR remove obsolete callout from consensus protocol
=> remove obsolete callout

content/api/grpc.md, content/api/json-rpc.md, static/swagger-ui/pactus.swagger.json
Updates API docs version 1.3.0
=> doc: update API docs

content/get-started/pactus-daemon.md, content/protocol/blockchain/address.md, content/protocol/blockchain/block.md
This PR fixes some invalid links in documents.
=> fix invalid links

content/get-started/become-a-validator.md
This PR updates become a validaotr post.
=> update become a validator post

content/protocol/consensus/protocol.md
This PR updates the consensus protocol and also adds the DECIDED message.
=> update consensus protocol

content/protocol/consensus/proof-of-stake.md
The image for SSPoS was missed.
=> update proof-of-stake doc

content/tutorials/software-verification.md
This PR adds a new tutorial for software verification using [cosign](https://github.com/sigstore/cosign).
=> How to Verify That Pactus Software Is Safe

content/tutorials/zero-fee-transactios.md
=> Fix a typo

content/tutorials/zero-fee-transactios.md
This PR changes the Max Pool size to 2000 as an example.
=> update zero-fee document

content/api/_index.md, content/get-started/_index.md, content/protocol/blockchain/_index.md, content/protocol/consensus/_index.md, content/protocol/transaction/_index.md, content/tutorials/_index.md, layouts/shortcodes/items.html
This PR makes index pages links dynamic.
=> make index page links dynamic

.gitignore, content/api/grpc.md, content/api/json-rpc.md, static/swagger-ui/pactus.swagger.json
This PR update documentation of website to `version 1.7.0`
=> update API documentation

go.mod, go.sum
This PR upgrades hextra to its latest version
=> upgrade hextra 

static/swagger-ui/pactus.swagger.json
This PR updates the public Bootstrap1 node path for the HTTP APIs.
=> update HTTP-API path for API doc

content/protocol/consensus/parameters.md
This PR updates the consensus parameters...
=> update parameters doc

content/protocol/consensus/protocol.md
=> add footnote for the message log
